/**
 * Seed quiz questions for Sport Sales Network Europe 2026 (EN)
 *
 * Purpose:
 * - Parse `docs/course_ideas/amanoba_course_sport_sales_network_europe_2026_questions.md`
 *   and upsert the course-specific QUIZZZ questions for Days 1–30 (7 questions/day).
 * - Keep the seed idempotent by matching on lessonId + question text.
 * - Populate the canonical lesson IDs generated by `seed-sport-sales-network-europe-2026-en.ts`.
 */

import { config } from 'dotenv';
import { resolve } from 'path';
import { readFileSync } from 'fs';
import { randomUUID } from 'crypto';

config({ path: resolve(process.cwd(), '.env.local') });

import connectDB from '../app/lib/mongodb';
import { Course, QuizQuestion, QuestionDifficulty, QuizQuestionType } from '../app/lib/models';

const COURSE_ID = 'SPORT_SALES_NETWORK_EUROPE_2026_EN';
const QUIZ_DOC_PATH = 'docs/course_ideas/amanoba_course_sport_sales_network_europe_2026_questions.md';

type ParsedQuestion = {
  question: string;
  options: string[];
  correctIndex: number;
};

type DayQuestions = {
  day: number;
  questions: ParsedQuestion[];
};

function parseQuestionDoc(text: string): DayQuestions[] {
  const blocks = text
    .split(/\n⸻+\n/)
    .map((block) => block.trim())
    .filter(Boolean);
  const parsed: DayQuestions[] = [];

  for (const block of blocks) {
    const dayMatch = block.match(/^Day\s+(\d+)/m);
    if (!dayMatch) {
      continue;
    }
    const day = Number(dayMatch[1]);
    const lines = block.split(/\r?\n/).map((line) => line.trim());
    const questions: ParsedQuestion[] = [];

    let i = 0;
    while (i < lines.length) {
      const line = lines[i];
      if (!line || !line.startsWith('Q')) {
        i += 1;
        continue;
      }
      const questionText = line.replace(/^Q\d+\.\s*/, '').trim();
      i += 1;

      const options: string[] = [];
      let correctIndex = -1;
      while (options.length < 4 && i < lines.length) {
        const optionLine = lines[i];
        i += 1;
        const match = optionLine.match(/^([A-D])\)\s*(.+)$/);
        if (!match) {
          continue;
        }
        let optionText = match[2].trim();
        const isCorrect = optionText.endsWith('✅');
        if (isCorrect) {
          optionText = optionText.replace(/\s*✅\s*$/, '').trim();
          correctIndex = options.length;
        }
        options.push(optionText);
      }
      if (options.length !== 4) {
        console.warn(`Skipping Day ${day} question because parsed ${options.length} options`, questionText);
        continue;
      }
      if (correctIndex < 0) {
        correctIndex = 0;
      }
      questions.push({ question: questionText, options, correctIndex });
    }

    if (questions.length > 0) {
      parsed.push({ day, questions });
    }
  }

  return parsed;
}

async function main() {
  await connectDB();
  const course = await Course.findOne({ courseId: COURSE_ID });
  if (!course) {
    throw new Error(`Course ${COURSE_ID} not found (run seed:sport-sales-network-europe-2026-en first)`);
  }

  const text = readFileSync(QUIZ_DOC_PATH, 'utf-8');
  const dayBlocks = parseQuestionDoc(text);
  let upserted = 0;

  const now = new Date();
  for (const block of dayBlocks) {
    const lessonId = `${COURSE_ID}_DAY_${String(block.day).padStart(2, '0')}`;
    for (const parsed of block.questions) {
      const filter = { lessonId, question: parsed.question };
      const hashtags = [`#sport-sales-network`, `#day${block.day}`, '#application'];
      const update = {
        $set: {
          question: parsed.question,
          options: parsed.options,
          correctIndex: parsed.correctIndex,
          difficulty: QuestionDifficulty.MEDIUM,
          category: 'Course Specific',
          questionType: QuizQuestionType.APPLICATION,
          hashtags,
          lessonId,
          courseId: course._id,
          isCourseSpecific: true,
          isActive: true,
          'metadata.updatedAt': now,
          relatedCourseIds: [],
        },
        $setOnInsert: {
          uuid: randomUUID(),
          showCount: 0,
          correctCount: 0,
          'metadata.createdAt': now,
        },
      };
      await QuizQuestion.findOneAndUpdate(filter, update, {
        upsert: true,
        new: true,
        setDefaultsOnInsert: true,
      });
      upserted += 1;
    }
  }

  console.log(`➜ Seed applied: upserted ${upserted} quiz questions for ${COURSE_ID}`);
}

main().catch((error) => {
  console.error('Seed failed:', error);
  process.exit(1);
});
